### ISSUE TITLE
Keren uga mirip sistem handler (plugins gitu) 

### ISSUE THREAD

**Issue by FBOTZ-YT** [zhwzein/Killua-Zoldyck#1]
Teruskan sampai kayak Hisoka-Morou 🚀

**Comment by zhwzein** [comment]
iyaa banh

**Comment by zhwzein** [comment]
> Teruskan sampai kayak Hisoka-Morou 🚀

iyaa banh

**Comment by zhwzein** [comment]
> Teruskan sampai kayak Hisoka-Morou 🚀

😎☝️☝️
