### ISSUE TITLE
fungsi addmsg, listcmd, addcmd

### ISSUE THREAD

**Issue by Rhosad29** [zhwzein/Killua-Zoldyck#13]
bang fungsi addmsg, listcmd apa ya ?
kok error habis reply gambar pakai addcmd, terus nulis listcmd langsung error

**Comment by zhwzein** [comment]
FIXED

**Comment by zhwzein** [comment]
![IMG_20220516_015325](https://user-images.githubusercontent.com/68224412/168489236-583a4ca4-2237-45e0-8a00-49d1c2d2248e.jpg)

Fixed
