### ISSUE TITLE
Facebook downloader

### ISSUE THREAD

**Issue by eRandomPerson** [zhwzein/Killua-Zoldyck#14]
Halo, ketika saya ingin mendownload video dari grup Facebook mengapa bot tidak mau mengirim videonya?, padahal grup tsb itu public, mohon bantuannya 🙏

**Comment by zhwzein** [comment]
![IMG_20220516_020537](https://user-images.githubusercontent.com/68224412/168489665-87dcadb9-8a0e-4f50-bbd4-a5925de88bf4.jpg)
Fixed make sure the link you sent is valid or starts with facebook.com/watch/?v=
