### ISSUE TITLE
Can't reply media

### ISSUE THREAD

**Issue by Rhosad29** [zhwzein/Killua-Zoldyck#16]
can't reply url, media like before

**Comment by zhwzein** [comment]
log?

**Comment by Rhosad29** [comment]
i already write npm i ffmpeg

![IMG_20220517_092616](https://user-images.githubusercontent.com/105351770/168715946-cc61ae73-0eb5-412f-a636-7994fb2469b9.jpg)
![IMG_20220517_092642](https://user-images.githubusercontent.com/105351770/168715960-8868d1af-eea4-4028-a0de-537fe9d2c31a.jpg)

**Comment by Rmdhn-20** [comment]
Gunakan buildpack ini di heroku anda

https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
https://github.com/clhuang/heroku-buildpack-webp-binaries.git

**Comment by Rhosad29** [comment]
gak pakai heroku bang

**Comment by zhwzein** [comment]
> i already write npm i ffmpeg
> 
> ![IMG_20220517_092616](https://user-images.githubusercontent.com/105351770/168715946-cc61ae73-0eb5-412f-a636-7994fb2469b9.jpg) ![IMG_20220517_092642](https://user-images.githubusercontent.com/105351770/168715960-8868d1af-eea4-4028-a0de-537fe9d2c31a.jpg)

ini heroku
