### ISSUE TITLE
Request 😀 

### ISSUE THREAD

**Issue by nexusNw** [zhwzein/Killua-Zoldyck#20]
Broh , can you make command 'update'
to update the latest push and edit of repo in deployed bot and ytmp3 and ytmp4 not working

**Comment by zhwzein** [comment]
> Broh , can you make command 'update' to update the latest push and edit of repo in deployed bot and ytmp3 and ytmp4 not working

update command availabe[ here](https://github.com/zhwzein/Killua-Zoldyck/commit/6f17b5106e29e0bcb63210e4b8f87b4dfc0f17d8)
also youtube fixed [here](https://github.com/zhwzein/Killua-Zoldyck/commit/e87a11f22a14ad1977efc8a172148886b7906384)
