### ISSUE TITLE
Req bang

### ISSUE THREAD

**Issue by Rmdhn-20** [zhwzein/Killua-Zoldyck#21]
Tambahin function autobio nya biar makin gemgeh kaya rest api nya🙏

**Comment by zhwzein** [comment]
autobio yg gmn banh

**Comment by Rmdhn-20** [comment]
Yg kaya di bio wa nya otomatis ke update banh.
Misal uptime nya udh 1jam an nah di bio wa ny ke update otomatis
Kek default nya kan gini: Hey there, I using the WhatsApp!
Nah itu auto update banh.. ngerti ga? Hehe
