### ISSUE TITLE
Getting error in deployment

### ISSUE THREAD

**Issue by IkshwakuPande** [zhwzein/Killua-Zoldyck#24]
![Pic of Error](https://user-images.githubusercontent.com/104565822/169738372-335ccb31-a1eb-450b-a546-116ec23df319.png)

**Comment by zhwzein** [comment]
did you have the last commit

**Comment by IkshwakuPande** [comment]
> did you have the last commit

yeah,I added api key and a littile edit

**Comment by IkshwakuPande** [comment]
![Screenshot (85)](https://user-images.githubusercontent.com/104565822/169752832-88262c40-61d1-4f63-a584-cc100ed47acc.png)

**Comment by zhwzein** [comment]
> 

emojimix ❤️❤️
or 
emojimix ❤️

**Comment by zhwzein** [comment]
> ![Screenshot (85)](https://user-images.githubusercontent.com/104565822/169752832-88262c40-61d1-4f63-a584-cc100ed47acc.png)

please read the usage example before using the command thanks
