### ISSUE TITLE
yo broh  . when using some commands , its not working and bot is crashing and reatarting.

### ISSUE THREAD

**Issue by nexusNw** [zhwzein/Killua-Zoldyck#27]
. for example:- when using update, sfwgif,self enable , dltmsg, etc 

and when using some img commands . the bot reply with 👇
![Screenshot_20220523-150614](https://user-images.githubusercontent.com/88531428/169790972-7517d839-9621-479a-938f-2a434ab51c53.png)
  (like the picture replied for command random holo)🐦

**Comment by zhwzein** [comment]
if the image command doesn't provide an image because the url you get is not valid from API

let me see your error log from your first comment

**Comment by nexusNw** [comment]
![Screenshot_20220526-163433](https://user-images.githubusercontent.com/88531428/170476002-1e3f46b1-5a54-4333-87b3-1fa2d1e9fcfc.png)


this is what shows in log when using command - sfwgif pat ,kiss etc
