### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by AliAryanTech** [zhwzein/Killua-Zoldyck#3]
Can you make Heroku deployment?

**Comment by zhwzein** [comment]
> Can you make Heroku deployment?

from now on heroku doesn't support clone from github I think

**Comment by hdiiofficial** [comment]
> > Can you make Heroku deployment?
> 
> from now on heroku doesn't support clone from github I think

Bisa klo bukn repo public cuma deploy klo nrach yg g bisa enthlh gw juga msi pke hroku

**Comment by AliAryanTech** [comment]
> > Can you make Heroku deployment?
> 
> from now on heroku doesn't support clone from github I think

Ya, I saw https://status.heroku.com/ 👀
Do you know any open Api website repo? 
I want to deploy https://zenzapis.xyz or any alternative

**Comment by Eximinati** [comment]
> > > Can you make Heroku deployment?
> > 
> > 
> > from now on heroku doesn't support clone from github I think
> 
> Ya, I saw https://status.heroku.com/ 👀 Do you know any open Api website repo? I want to deploy https://zenzapis.xyz or any alternative

you can use zenzapis.xyz
