### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SamPandey001** [zhwzein/Killua-Zoldyck#31]
Just 2 sec after deploying on Heroku ![Screenshot (87)](https://user-images.githubusercontent.com/104565822/170818042-6b574a71-c95c-4d00-8a74-63e143829bf0.png)
![Screenshot (88)](https://user-images.githubusercontent.com/104565822/170818070-7b5d66ae-35ee-4ff1-b6c7-c552f00dba76.png)

**Comment by IkshwakuPande** [comment]
?

**Comment by zhwzein** [comment]
get your Heroku IP and set it to web api read this [wiki](https://github.com/zhwzein/Killua-Zoldyck/wiki/Get-IP-access)
