### ISSUE TITLE
kalo run di termux lemot itu kenapa ya bang?

### ISSUE THREAD

**Issue by Mr-XsZ1** [zhwzein/Killua-Zoldyck#36]
bantu

**Comment by zhwzein** [comment]
jaringan lag

**Comment by ngewa** [comment]
![Screenshot_20220611-150204_Termux-picsay](https://user-images.githubusercontent.com/92763809/173179271-f256db3c-9327-40ef-b50f-bcfe584c0594.jpg)

**Comment by Bintangp02** [comment]
> ![Screenshot_20220611-150204_Termux-picsay](https://user-images.githubusercontent.com/92763809/173179271-f256db3c-9327-40ef-b50f-bcfe584c0594.jpg) kenapa tu bang

Semua terjadi karna Faktor scan yang lama sehingga tidak terpandai dengan baik, ke 2 pastikan koneksi anda cepat koneksi sedikit lemot adalah akibat keterlambatan terkirimnya pesan.
