### ISSUE TITLE
Pesan dari group terkadang tidak mau direspon

### ISSUE THREAD

**Issue by ahmadkeren** [zhwzein/Killua-Zoldyck#4]
Apakah ada solusi, terkadang (cukup sering) pesan dari group tidak dapat direspon oleh botnya.. tapi di terminal pesan yang dikirim user teridentifikasi masuk..

**Comment by zhwzein** [comment]
first, if you make a request to the web api, make sure your apikey has not reached the usage limit

**Comment by ahmadkeren** [comment]
Any solution for this error:
1. Failed to decrypt message with any known session...
2. Closing open session in favor of incoming prekey bundle
2022-04-23T03:15:21.814035+00:00 app[worker.1]: Closing session: SessionEntry {...

**Comment by zhwzein** [comment]
better delete all existing messages, then re-scan the QR code
