### ISSUE TITLE
EROR RUN FOR RAILWAY & OKTETO

### ISSUE THREAD

**Issue by Bintangp02** [zhwzein/Killua-Zoldyck#42]
`====================================
Banned Dependency Detected!
====================================`
 
```nekos```
 
`Please remove this dependency from your project to use it on Railway`

bagain mana saya tidak mengetahuinya eror dan stuck menjadi masalah baru,
bagaimana saya memperbaikinya??
Bagain mana kata dari `nekos` Berada??

Trimakasih.

**Comment by ahmadkeren** [comment]
commands/randomanime/animemenu.js
commands/nekoslife/sfwmenu.js
commands/nekoslife/sfwimage.js
commands/randomanime/randomanime.js
