### ISSUE TITLE
how to use api

### ISSUE THREAD

**Issue by salsawij** [zhwzein/Killua-Zoldyck#51]
hello there, I want to know how to use the available zenzapi, is there any guide how to use?

**Comment by NugrahaMP** [comment]
do u use termux or heroku?
if u use termux, u should register to zenzapi first and then u got the apikey. Copy the apikey. Then open your termux, type pkg install mc. and then cd Killua-Zoldyck and then type mc. The output should be file of the bot. search for 'config.json', and press edit button. It should be open the config.json file. Then edit the "apikey" in 
"APIs": {
    "zenz": "https://zenzapis.xyz",
    "apikey": "YOURAPIKEY"
just delete the 'YOURAPIKEY' and paste your apikey

**Comment by salsawij** [comment]
> do u use termux or heroku? if u use termux, u should register to zenzapi first and then u got the apikey. Copy the apikey. Then open your termux, type pkg install mc. and then cd Killua-Zoldyck and then type mc. The output should be file of the bot. search for 'config.json', and press edit button. It should be open the config.json file. Then edit the "apikey" in "APIs": { "zenz": "https://zenzapis.xyz", "apikey": "YOURAPIKEY" just delete the 'YOURAPIKEY' and paste your apikey

ahh, alright. Thanks for the info!!
