### ISSUE TITLE
Ask Error

### ISSUE THREAD

**Issue by udeannn** [zhwzein/Killua-Zoldyck#52]
permisi bang mau tanya ini kenapa ya bang?

![image](https://user-images.githubusercontent.com/101232052/192113169-a7eaeefc-c06a-4b39-a1e8-98991f9c5f07.png)

**Comment by salsawij** [comment]
+1

**Comment by udeannn** [comment]
+1 kak? Maksudnya bagaimana ya kak?

**Comment by udeannn** [comment]
> +1

+1 ? Maksudnya bagaimana ya kak? Maaf kurang paham

**Comment by FatihArridho** [comment]
done fix
