### ISSUE TITLE
Beberapa masalah ketika run di termux

### ISSUE THREAD

**Issue by axolotlextnd** [zhwzein/Killua-Zoldyck#53]
infonya kak, pas jalanin perintah buat tampilin menu, menunya muncul cuma di nomor sendiri (nomor dipake jalanin bot nya) sama setelah itu bot crash (sehabis jalanin perintah apapun bot langsung crash)

**Comment by Ajimiko** [comment]
> infonya kak, pas jalanin perintah buat tampilin menu, menunya muncul cuma di nomor sendiri (nomor dipake jalanin bot nya) sama setelah itu bot crash (sehabis jalanin perintah apapun bot langsung crash)

Tinggal diganti button nya yang biasa

**Comment by axolotlextnd** [comment]
> > infonya kak, pas jalanin perintah buat tampilin menu, menunya muncul cuma di nomor sendiri (nomor dipake jalanin bot nya) sama setelah itu bot crash (sehabis jalanin perintah apapun bot langsung crash)
> 
> Tinggal diganti button nya yang biasa

gimana tuh kak?
