### ISSUE TITLE
Fitur downloader banyak error

### ISSUE THREAD

**Issue by bucol** [zhwzein/Killua-Zoldyck#61]
Kebanyakan seperti ini terus

![Screenshot_6](https://user-images.githubusercontent.com/37924597/215122630-0d6d993c-f482-4bf3-8ca9-5cffb04ca7b7.png)

**Comment by cantiir2** [comment]
Jangan malas, perbaiki sendiri

**Comment by zhwzein** [comment]
> Jangan malas, perbaiki sendiri

bagus
