### ISSUE TITLE
Cara Fix Device Logged Out, Please Scan Again And Run.

### ISSUE THREAD

**Issue by rtacode** [zhwzein/Killua-Zoldyck#62]
![Screenshot_2023-02-08-01-26-19-75_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/123898796/217333447-930233fe-92b7-4ccb-acd4-dc50db302c9e.jpg)

Cara Fixnya gmna ya ?

**Comment by cantiir2** [comment]
tambahin folder session
