### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Cosm1cBug** [zhwzein/Killua-Zoldyck#64]
Hi I'm getting this error while running the bot, sometimes it doesn't affect the bot but sometimes it stops the bot.

{"level":40,"time":"2023-02-10T13:52:58.685Z","pid":7080,"hostname":"BUGGYBOX","stack":"Error: mutex start\n    at C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:15:31\n    at Object.mutex (C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:35:15)\n    at handleMessage (C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:451:29)\n    at execTask (C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:554:20)\n    at processNodeWithBuffer (C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:551:15)\n    at WebSocket.<anonymous> (C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:560:9)\n    at WebSocket.emit (node:events:527:28)\n    at C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:222:35\n    at Object.decodeFrame (C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (C:\\Users\\aru\\OneDrive\\Desktop\\Killua-Zoldyck\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}

**Comment by zhwzein** [comment]
fixed next update
