### ISSUE TITLE
How can i deploy this git in heroku , plz tell?

### ISSUE THREAD

**Issue by nexusNw** [zhwzein/Killua-Zoldyck#7]
how can I deploy this git in heroku😄?

**Comment by gamingrkp** [comment]
> how can I deploy this git in heroku😄?

there too many tutorial in youtube... why u not see youtube lmao

**Comment by nexusNw** [comment]
> 

but i tried to deploy through heroku ,but failed everytime😭 i dont know why . and i dont know how to get session😭 
if anything wrong in this git ( github.com/nexusNw/Asta) plz tell me

**Comment by gamingrkp** [comment]
> > 
> 
> but i tried to deploy through heroku ,but failed everytime😭 i dont know why . and i dont know how to get session😭 if anything wrong in this git ( github.com/nexusNw/Asta) plz tell me

get session you need scan use whatsapp ( u can scan in heroku or in your pc my advice you scan in ur pc then go ,gitignore file delete tmp/killua-multi ( you need private your github repo  if you want to use this method )  )
