### ISSUE TITLE
Showing Cant find module 'Chalk' while deploying via termux

### ISSUE THREAD

**Issue by nexusNw** [zhwzein/Killua-Zoldyck#8]
![Eror](https://user-images.githubusercontent.com/88531428/165470730-2ad94c3b-20b1-4dd9-9c90-67d6c28f604d.png)

**Comment by zhwzein** [comment]
npm i chalk?

**Comment by DikaArdnt** [comment]
> ![Eror](https://user-images.githubusercontent.com/88531428/165470730-2ad94c3b-20b1-4dd9-9c90-67d6c28f604d.png)

# Use npm
npm install chalk

# Use yarn
yarn add chalk
