### ISSUE TITLE
Pesan Sering Tidak dapat Terkirim ke Group

### ISSUE THREAD

**Issue by ahmadkeren** [zhwzein/Killua-Zoldyck#9]
Permisi, saya izin mereport bahwasannya pesan sangat sering tidak dapat terkirim ke group tertentu (kumat")
Saya debug (console.log) tidak ada masalah.. berikut screenshootnya responnya:
![Screen Shot 2022-05-03 at 16 26 37](https://user-images.githubusercontent.com/49072140/166431645-d65fe679-9fc2-42d7-88c5-a83c274106c7.png)
Berikut kodingannya:
![Screen Shot 2022-05-03 at 16 30 38](https://user-images.githubusercontent.com/49072140/166431722-4d6ed366-d5e4-4be5-854f-7411df6090e6.png)
Apakah ada solusi?
Terima kasih...
Catatan: permasalahan ini "cuma" muncul di group (cukup sering: dalam artian, terkadang bisa terkirim, terkadang tidak) dan tidak ada masalah jika chat secara pribadi (PM).

**Comment by ahmadkeren** [comment]
Untuk fungsi m.replynya, saya ubah seperti ini..

![Screen Shot 2022-05-03 at 16 33 25](https://user-images.githubusercontent.com/49072140/166432077-d19766c2-c937-4801-a82a-f74c65272863.png)

**Comment by zhwzein** [comment]
use START.bat then BOT will automatically restart when there is an error
